### ISSUE TITLE
Compiler error on OS X

### ISSUE THREAD

**Issue by rik** [mythmon/edwin#14] opened 2015-04-22 09:33 UTC
`Error: EMFILE, open '/Users/rik24d/code/edwin/node_modules/react/package.json'`

This seems to be a file limit issue but I can't seem to fix it with various tips I'm seeing around the internet.
https://github.com/Banno/grunt-coffeeify/issues/6#issuecomment-16054139 for example is not enough on my machine :(

**Comment by mythmon** [comment] 2015-04-22 15:13
When does this happen? What are you doing at the time?

**Comment by rik** [comment] 2015-04-23 15:26
Sorry, I filed this in a bit of a hurry.

This happens when I load `http://localhost:8000`.
I've tried the command that fails in my terminal:

``` shell
./node_modules/.bin/browserify -t babelify ./static/js/client.browserify.js > ./static/js/client.browserify.browserified.js
```

It fails the same way unless I use `ulimit -n 2560`.

**Comment by mythmon** [comment] 2015-04-23 16:20
Is there a stack trace that goes with this? I'm having trouble reproducing this. My ulimit is set to "unlimited", and I haven't figured out how to limit it to test this.

**Comment by willkg** [comment] 2015-06-26 01:03
In an alternate universe, Edwin is supreme omnipotent ruler of all project status report systems. It spends its time riding giraffes in the hunt and eating wasabi peanuts. Due to the nature of this universe and its complete inability to comprehend ulimit-related bugs, I'm closing this out before we unintentionally insult them and inadvertently start a war that wipes our universe out.

**Closed as completed by willkg** 2015-06-26 01:03 UTC
